apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-sentinel
  labels:
    app: redis-sentinel
data:
  sentinel.conf: |
    # sentinel config
    sentinel monitor mymaster redis-0.redis 6379 2 
    sentinel down-after-milliseconds mymaster 60000 
    sentinel failover-timeout mymaster 180000 
    sentinel parallel-syncs mymaster 1 
    bind 0.0.0.0
    protected-mode no 
